// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PawPuff_Management.Models.EfModels;

[Table("admins_permissions")]
[Index("AdminsId", "PermissionName", Name = "UQ_admins_permissions_admin_permission", IsUnique = true)]
public partial class AdminsPermission
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("admins_id")]
    public int AdminsId { get; set; }

    [Required]
    [Column("permission_name")]
    [StringLength(100)]
    public string PermissionName { get; set; }

    [ForeignKey("AdminsId")]
    [InverseProperty("AdminsPermissions")]
    public virtual Admin Admins { get; set; }
}