// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PawPuff_Management.Models.EfModels;

[Table("admins")]
[Index("Account", Name = "UQ_admins_account", IsUnique = true)]
[Index("Email", Name = "UQ_admins_email", IsUnique = true)]
public partial class Admin
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("account")]
    [StringLength(50)]
    [Unicode(false)]
    public string Account { get; set; }

    [Required]
    [Column("password_hash")]
    [StringLength(255)]
    [Unicode(false)]
    public string PasswordHash { get; set; }

    [Required]
    [Column("nickname")]
    [StringLength(100)]
    public string Nickname { get; set; }

    [Required]
    [Column("email")]
    [StringLength(100)]
    public string Email { get; set; }

    [Column("is_active")]
    public bool IsActive { get; set; }

    [Column("created_at", TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column("admin_comment")]
    [StringLength(100)]
    public string AdminComment { get; set; }

    [Column("admin_updated_at", TypeName = "datetime")]
    public DateTime? AdminUpdatedAt { get; set; }

    [Column("modified_by_admin_id")]
    public int? ModifiedByAdminId { get; set; }

    [InverseProperty("Admins")]
    public virtual ICollection<AdminsClock> AdminsClocks { get; set; } = new List<AdminsClock>();

    [InverseProperty("Admins")]
    public virtual ICollection<AdminsPermission> AdminsPermissions { get; set; } = new List<AdminsPermission>();

    [InverseProperty("ModifiedByAdmin")]
    public virtual ICollection<Article> Articles { get; set; } = new List<Article>();

    [InverseProperty("ModifiedByAdmin")]
    public virtual ICollection<Comment> Comments { get; set; } = new List<Comment>();

    [InverseProperty("ModifiedByAdmin")]
    public virtual ICollection<Admin> InverseModifiedByAdmin { get; set; } = new List<Admin>();

    [ForeignKey("ModifiedByAdminId")]
    [InverseProperty("InverseModifiedByAdmin")]
    public virtual Admin ModifiedByAdmin { get; set; }

    [InverseProperty("Admin")]
    public virtual ICollection<Notification> NotificationAdmins { get; set; } = new List<Notification>();

    [InverseProperty("SenderAdmin")]
    public virtual ICollection<Notification> NotificationSenderAdmins { get; set; } = new List<Notification>();

    [InverseProperty("ModifiedByAdmin")]
    public virtual ICollection<PointTransaction> PointTransactions { get; set; } = new List<PointTransaction>();

    [InverseProperty("ModifiedByAdmin")]
    public virtual ICollection<Product> Products { get; set; } = new List<Product>();

    [InverseProperty("Admin")]
    public virtual ICollection<TicketMessage> TicketMessages { get; set; } = new List<TicketMessage>();

    [InverseProperty("Admin")]
    public virtual ICollection<Ticket> Tickets { get; set; } = new List<Ticket>();

    [InverseProperty("ModifiedByAdmin")]
    public virtual ICollection<User> Users { get; set; } = new List<User>();
}