// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PawPuff_Management.Models.EfModels;

[Table("admins_clock")]
[Index("AdminsId", "WorkDate", Name = "UQ_admins_clock_admin_work_date", IsUnique = true)]
public partial class AdminsClock
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("admins_id")]
    public int AdminsId { get; set; }

    [Column("work_date")]
    public DateOnly WorkDate { get; set; }

    [Column("clock_in_time", TypeName = "datetime")]
    public DateTime ClockInTime { get; set; }

    [Column("clock_out_time", TypeName = "datetime")]
    public DateTime? ClockOutTime { get; set; }

    [ForeignKey("AdminsId")]
    [InverseProperty("AdminsClocks")]
    public virtual Admin Admins { get; set; }
}