// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PawPuff_Management.Models.EfModels;

[Table("article_images")]
[Index("ImageName", Name = "IX_article_images", IsUnique = true)]
public partial class ArticleImage
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("article_id")]
    public int ArticleId { get; set; }

    [Required]
    [Column("image_name")]
    [StringLength(50)]
    public string ImageName { get; set; }

    [Column("image_order")]
    public int ImageOrder { get; set; }

    [ForeignKey("ArticleId")]
    [InverseProperty("ArticleImages")]
    public virtual Article Article { get; set; }
}