// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PawPuff_Management.Models.EfModels;

[Table("articles")]
public partial class Article
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("user_id")]
    public int? UserId { get; set; }

    [Column("category_id")]
    public int CategoryId { get; set; }

    [Required]
    [Column("title")]
    [StringLength(100)]
    public string Title { get; set; }

    [Required]
    [Column("article_content")]
    [StringLength(4000)]
    public string ArticleContent { get; set; }

    [Column("is_active")]
    public bool IsActive { get; set; }

    [Column("created_at", TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column("updated_at", TypeName = "datetime")]
    public DateTime? UpdatedAt { get; set; }

    [Column("admin_comment")]
    [StringLength(100)]
    public string AdminComment { get; set; }

    [Column("admin_updated_at", TypeName = "datetime")]
    public DateTime? AdminUpdatedAt { get; set; }

    [Column("modified_by_admin_id")]
    public int? ModifiedByAdminId { get; set; }

    [InverseProperty("Article")]
    public virtual ICollection<ArticleImage> ArticleImages { get; set; } = new List<ArticleImage>();

    [InverseProperty("Article")]
    public virtual ICollection<ArticleLike> ArticleLikes { get; set; } = new List<ArticleLike>();

    [InverseProperty("Article")]
    public virtual ICollection<ArticleSafe> ArticleSaves { get; set; } = new List<ArticleSafe>();

    [ForeignKey("CategoryId")]
    [InverseProperty("Articles")]
    public virtual ArticleCategory Category { get; set; }

    [InverseProperty("Article")]
    public virtual ICollection<Comment> Comments { get; set; } = new List<Comment>();

    [ForeignKey("ModifiedByAdminId")]
    [InverseProperty("Articles")]
    public virtual Admin ModifiedByAdmin { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("Articles")]
    public virtual User User { get; set; }
}