// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PawPuff_Management.Models.EfModels;

[Table("article_likes")]
[Index("ArticleId", "UserId", Name = "UQ_article_likes_article_user", IsUnique = true)]
public partial class ArticleLike
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("article_id")]
    public int ArticleId { get; set; }

    [Column("user_id")]
    public int UserId { get; set; }

    [Column("created_at", TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column("is_active")]
    public bool IsActive { get; set; }

    [ForeignKey("ArticleId")]
    [InverseProperty("ArticleLikes")]
    public virtual Article Article { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("ArticleLikes")]
    public virtual User User { get; set; }
}