// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PawPuff_Management.Models.EfModels;

[Table("doll_accessory")]
[Index("Name", Name = "IX_doll_accessory", IsUnique = true)]
[Index("LineImageName", Name = "IX_doll_accessory_1", IsUnique = true)]
[Index("MaskImageName", Name = "IX_doll_accessory_2", IsUnique = true)]
public partial class DollAccessory
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("name")]
    [StringLength(100)]
    public string Name { get; set; }

    [Required]
    [Column("line_image_name")]
    [StringLength(50)]
    public string LineImageName { get; set; }

    [Required]
    [Column("mask_image_name")]
    [StringLength(50)]
    public string MaskImageName { get; set; }

    [Column("sort_order")]
    public int SortOrder { get; set; }

    [InverseProperty("DollAccessory")]
    public virtual Product Product { get; set; }

    [InverseProperty("DollAccessory1")]
    public virtual ICollection<UserDollConfig> UserDollConfigDollAccessory1s { get; set; } = new List<UserDollConfig>();

    [InverseProperty("DollAccessory2")]
    public virtual ICollection<UserDollConfig> UserDollConfigDollAccessory2s { get; set; } = new List<UserDollConfig>();

    [InverseProperty("DollAccessory3")]
    public virtual ICollection<UserDollConfig> UserDollConfigDollAccessory3s { get; set; } = new List<UserDollConfig>();
}