// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PawPuff_Management.Models.EfModels;

[Table("doll_colors")]
[Index("HexCode", Name = "UQ_doll_colors_hex_code", IsUnique = true)]
[Index("Name", Name = "UQ_doll_colors_name", IsUnique = true)]
public partial class DollColor
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("name")]
    [StringLength(100)]
    public string Name { get; set; }

    [Required]
    [Column("hex_code")]
    [StringLength(9)]
    [Unicode(false)]
    public string HexCode { get; set; }

    [InverseProperty("DollColors")]
    public virtual Product Product { get; set; }

    [InverseProperty("DollAccessory1Color")]
    public virtual ICollection<UserDollConfig> UserDollConfigDollAccessory1Colors { get; set; } = new List<UserDollConfig>();

    [InverseProperty("DollAccessory2Color")]
    public virtual ICollection<UserDollConfig> UserDollConfigDollAccessory2Colors { get; set; } = new List<UserDollConfig>();

    [InverseProperty("DollAccessory3Color")]
    public virtual ICollection<UserDollConfig> UserDollConfigDollAccessory3Colors { get; set; } = new List<UserDollConfig>();

    [InverseProperty("DollBodyColor")]
    public virtual ICollection<UserDollConfig> UserDollConfigDollBodyColors { get; set; } = new List<UserDollConfig>();
}