// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PawPuff_Management.Models.EfModels;

[Table("doll_body")]
[Index("Name", Name = "IX_doll_body", IsUnique = true)]
[Index("ImageName", Name = "IX_doll_body_1", IsUnique = true)]
public partial class DollBody
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("name")]
    [StringLength(100)]
    public string Name { get; set; }

    [Required]
    [Column("image_name")]
    [StringLength(50)]
    public string ImageName { get; set; }

    [InverseProperty("DollBody")]
    public virtual Product Product { get; set; }

    [InverseProperty("DollBody")]
    public virtual ICollection<UserDollConfig> UserDollConfigs { get; set; } = new List<UserDollConfig>();
}