// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PawPuff_Management.Models.EfModels;

[Table("faqs")]
[Index("Question", Name = "IX_faqs", IsUnique = true)]
public partial class Faq
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("type")]
    public int Type { get; set; }

    [Required]
    [Column("question")]
    [StringLength(100)]
    public string Question { get; set; }

    [Required]
    [Column("answer")]
    [StringLength(1000)]
    public string Answer { get; set; }

    [Column("sort_order")]
    public int SortOrder { get; set; }

    [Column("is_active")]
    public bool IsActive { get; set; }

    [Column("created_at", TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column("updated_at", TypeName = "datetime")]
    public DateTime? UpdatedAt { get; set; }
}