// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PawPuff_Management.Models.EfModels;

[Table("notifications")]
public partial class Notification
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("user_id")]
    public int? UserId { get; set; }

    [Column("admin_id")]
    public int? AdminId { get; set; }

    [Required]
    [Column("type")]
    [StringLength(50)]
    [Unicode(false)]
    public string Type { get; set; }

    [Required]
    [Column("notification_content")]
    [StringLength(100)]
    public string NotificationContent { get; set; }

    [Column("is_read")]
    public bool IsRead { get; set; }

    [Column("link_url")]
    [StringLength(2048)]
    public string LinkUrl { get; set; }

    [Column("created_at", TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column("sender_admin_id")]
    public int? SenderAdminId { get; set; }

    [ForeignKey("AdminId")]
    [InverseProperty("NotificationAdmins")]
    public virtual Admin Admin { get; set; }

    [ForeignKey("SenderAdminId")]
    [InverseProperty("NotificationSenderAdmins")]
    public virtual Admin SenderAdmin { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("Notifications")]
    public virtual User User { get; set; }
}