// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace PawPuff_Management.Models.EfModels;

public partial class PawPuffContext : DbContext
{
    public PawPuffContext(DbContextOptions<PawPuffContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Admin> Admins { get; set; }

    public virtual DbSet<AdminsClock> AdminsClocks { get; set; }

    public virtual DbSet<AdminsPermission> AdminsPermissions { get; set; }

    public virtual DbSet<Article> Articles { get; set; }

    public virtual DbSet<ArticleCategory> ArticleCategories { get; set; }

    public virtual DbSet<ArticleImage> ArticleImages { get; set; }

    public virtual DbSet<ArticleLike> ArticleLikes { get; set; }

    public virtual DbSet<ArticleSafe> ArticleSaves { get; set; }

    public virtual DbSet<Comment> Comments { get; set; }

    public virtual DbSet<DollAccessory> DollAccessories { get; set; }

    public virtual DbSet<DollBody> DollBodies { get; set; }

    public virtual DbSet<DollColor> DollColors { get; set; }

    public virtual DbSet<DollFrame> DollFrames { get; set; }

    public virtual DbSet<Faq> Faqs { get; set; }

    public virtual DbSet<Notification> Notifications { get; set; }

    public virtual DbSet<PointChangeType> PointChangeTypes { get; set; }

    public virtual DbSet<PointTransaction> PointTransactions { get; set; }

    public virtual DbSet<Product> Products { get; set; }

    public virtual DbSet<Ticket> Tickets { get; set; }

    public virtual DbSet<TicketMessage> TicketMessages { get; set; }

    public virtual DbSet<TicketMessagesImage> TicketMessagesImages { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserDollConfig> UserDollConfigs { get; set; }

    public virtual DbSet<UserProduct> UserProducts { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Admin>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__admins__3213E83F1BB68F59");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.IsActive).HasDefaultValue(true);

            entity.HasOne(d => d.ModifiedByAdmin).WithMany(p => p.InverseModifiedByAdmin).HasConstraintName("FK_admins_modified_by_admin");
        });

        modelBuilder.Entity<AdminsClock>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__admins_c__3213E83F0B845DA4");

            entity.HasOne(d => d.Admins).WithMany(p => p.AdminsClocks)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_admins_clock_admins");
        });

        modelBuilder.Entity<AdminsPermission>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__admins_p__3213E83FDA93A32A");

            entity.HasOne(d => d.Admins).WithMany(p => p.AdminsPermissions)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_admins_permissions_admins");
        });

        modelBuilder.Entity<Article>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__articles__3213E83F657842F4");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__articles__create__17036CC0");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF__articles__is_act__160F4887");

            entity.HasOne(d => d.Category).WithMany(p => p.Articles)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_articles_article_categories");

            entity.HasOne(d => d.ModifiedByAdmin).WithMany(p => p.Articles).HasConstraintName("FK_articles_modified_by_admin");

            entity.HasOne(d => d.User).WithMany(p => p.Articles).HasConstraintName("FK_articles_users");
        });

        modelBuilder.Entity<ArticleCategory>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__article___3213E83F06A8D800");

            entity.Property(e => e.IsActive).HasDefaultValue(true);
        });

        modelBuilder.Entity<ArticleImage>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__article___3213E83F38885EF7");

            entity.Property(e => e.ImageOrder)
                .HasDefaultValue(1)
                .HasAnnotation("Relational:DefaultConstraintName", "DF__article_i__image__1CBC4616");

            entity.HasOne(d => d.Article).WithMany(p => p.ArticleImages)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_article_images_articles");
        });

        modelBuilder.Entity<ArticleLike>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__article___3213E83F02C0523E");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.IsActive).HasDefaultValue(true);

            entity.HasOne(d => d.Article).WithMany(p => p.ArticleLikes)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_article_likes_articles");

            entity.HasOne(d => d.User).WithMany(p => p.ArticleLikes)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_article_likes_users");
        });

        modelBuilder.Entity<ArticleSafe>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__article___3213E83F59338C22");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.IsActive).HasDefaultValue(true);

            entity.HasOne(d => d.Article).WithMany(p => p.ArticleSaves)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_article_saves_articles");

            entity.HasOne(d => d.User).WithMany(p => p.ArticleSaves)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_article_saves_users");
        });

        modelBuilder.Entity<Comment>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__comments__3213E83FD502C80E");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__comments__create__22751F6C");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF__comments__is_act__2180FB33");

            entity.HasOne(d => d.Article).WithMany(p => p.Comments)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_comments_articles");

            entity.HasOne(d => d.ModifiedByAdmin).WithMany(p => p.Comments).HasConstraintName("FK_comments_modified_by_admin");

            entity.HasOne(d => d.ParentComment).WithMany(p => p.InverseParentComment).HasConstraintName("FK_comments_parent_comment");

            entity.HasOne(d => d.User).WithMany(p => p.Comments).HasConstraintName("FK_comments_users");
        });

        modelBuilder.Entity<DollAccessory>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__doll_acc__3213E83FFB52147B");

            entity.Property(e => e.SortOrder)
                .HasDefaultValue(1)
                .HasAnnotation("Relational:DefaultConstraintName", "DF__doll_acce__sort___656C112C");
        });

        modelBuilder.Entity<DollBody>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__doll_bod__3213E83F868EA069");
        });

        modelBuilder.Entity<DollColor>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__doll_col__3213E83F6EC664D5");

            entity.Property(e => e.HexCode).IsFixedLength();
        });

        modelBuilder.Entity<DollFrame>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__doll_fra__3213E83FFE2C77E8");

            entity.Property(e => e.IsSquare)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF__doll_fram__is_sq__6E01572D");
        });

        modelBuilder.Entity<Faq>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__faqs__3213E83F940A0D3A");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.SortOrder).HasDefaultValue(1);
        });

        modelBuilder.Entity<Notification>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__notifica__3213E83F417C0742");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Admin).WithMany(p => p.NotificationAdmins).HasConstraintName("FK_notifications_admins");

            entity.HasOne(d => d.SenderAdmin).WithMany(p => p.NotificationSenderAdmins).HasConstraintName("FK_notifications_sender_admin");

            entity.HasOne(d => d.User).WithMany(p => p.Notifications).HasConstraintName("FK_notifications_users");
        });

        modelBuilder.Entity<PointChangeType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__point_ch__3213E83F5C48F1C8");

            entity.Property(e => e.DefaultValue)
                .HasDefaultValue(0)
                .HasAnnotation("Relational:DefaultConstraintName", "DF__point_cha__defau__0E6E26BF");
            entity.Property(e => e.IsFixed)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF__point_cha__is_fi__0D7A0286");
        });

        modelBuilder.Entity<PointTransaction>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__point_tr__3213E83F01A06DB1");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__point_tra__creat__14E61A24");

            entity.HasOne(d => d.ChangeType).WithMany(p => p.PointTransactions)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_point_transactions_change_types");

            entity.HasOne(d => d.ModifiedByAdmin).WithMany(p => p.PointTransactions).HasConstraintName("FK_point_transactions_modified_by_admin");

            entity.HasOne(d => d.User).WithMany(p => p.PointTransactions)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_point_transactions_users");

            entity.HasOne(d => d.UserProduct).WithMany(p => p.PointTransactions).HasConstraintName("FK_point_transactions_user_products");
        });

        modelBuilder.Entity<Product>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__products__3213E83F8381F71B");

            entity.Property(e => e.IsActive).HasDefaultValue(true);

            entity.HasOne(d => d.DollAccessory).WithOne(p => p.Product).HasConstraintName("FK_products_doll_accessory");

            entity.HasOne(d => d.DollBody).WithOne(p => p.Product).HasConstraintName("FK_products_doll_body");

            entity.HasOne(d => d.DollColors).WithOne(p => p.Product).HasConstraintName("FK_products_doll_colors");

            entity.HasOne(d => d.DollFrames).WithOne(p => p.Product).HasConstraintName("FK_products_doll_frames");

            entity.HasOne(d => d.ModifiedByAdmin).WithMany(p => p.Products).HasConstraintName("FK_products_modified_by_admin");
        });

        modelBuilder.Entity<Ticket>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tickets__3213E83FD8AFBB73");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Admin).WithMany(p => p.Tickets).HasConstraintName("FK_tickets_admins");

            entity.HasOne(d => d.User).WithMany(p => p.Tickets)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tickets_users");
        });

        modelBuilder.Entity<TicketMessage>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ticket_m__3213E83FD2928C59");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Admin).WithMany(p => p.TicketMessages).HasConstraintName("FK_ticket_messages_admins");

            entity.HasOne(d => d.Ticket).WithMany(p => p.TicketMessages)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ticket_messages_tickets");

            entity.HasOne(d => d.User).WithMany(p => p.TicketMessages).HasConstraintName("FK_ticket_messages_users");
        });

        modelBuilder.Entity<TicketMessagesImage>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ticket_m__3213E83F207A81B8");

            entity.Property(e => e.ImageOrder)
                .HasDefaultValue(1)
                .HasAnnotation("Relational:DefaultConstraintName", "DF__ticket_me__image__503BEA1C");

            entity.HasOne(d => d.TicketMessages).WithMany(p => p.TicketMessagesImages)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ticket_messages_images_ticket_messages");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__users__3213E83FB8BBFD3E");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__users__created_a__5629CD9C");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF__users__is_active__5535A963");
            entity.Property(e => e.PointBalance).HasAnnotation("Relational:DefaultConstraintName", "DF__users__point_bal__5441852A");

            entity.HasOne(d => d.ActiveDollConfigs).WithMany(p => p.Users).HasConstraintName("FK_users_active_doll_configs");

            entity.HasOne(d => d.ActiveDollFrame).WithMany(p => p.Users).HasConstraintName("FK_users_active_doll_frame");

            entity.HasOne(d => d.ModifiedByAdmin).WithMany(p => p.Users).HasConstraintName("FK_users_modified_by_admin");
        });

        modelBuilder.Entity<UserDollConfig>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__user_dol__3213E83F55A00B34");

            entity.HasOne(d => d.DollAccessory1Color).WithMany(p => p.UserDollConfigDollAccessory1Colors).HasConstraintName("FK_user_doll_configs_accessory1_color");

            entity.HasOne(d => d.DollAccessory1).WithMany(p => p.UserDollConfigDollAccessory1s).HasConstraintName("FK_user_doll_configs_accessory1");

            entity.HasOne(d => d.DollAccessory2Color).WithMany(p => p.UserDollConfigDollAccessory2Colors).HasConstraintName("FK_user_doll_configs_accessory2_color");

            entity.HasOne(d => d.DollAccessory2).WithMany(p => p.UserDollConfigDollAccessory2s).HasConstraintName("FK_user_doll_configs_accessory2");

            entity.HasOne(d => d.DollAccessory3Color).WithMany(p => p.UserDollConfigDollAccessory3Colors).HasConstraintName("FK_user_doll_configs_accessory3_color");

            entity.HasOne(d => d.DollAccessory3).WithMany(p => p.UserDollConfigDollAccessory3s).HasConstraintName("FK_user_doll_configs_accessory3");

            entity.HasOne(d => d.DollBodyColor).WithMany(p => p.UserDollConfigDollBodyColors).HasConstraintName("FK_user_doll_configs_body_color");

            entity.HasOne(d => d.DollBody).WithMany(p => p.UserDollConfigs)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_user_doll_configs_doll_body");

            entity.HasOne(d => d.User).WithMany(p => p.UserDollConfigs)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_user_doll_configs_users");
        });

        modelBuilder.Entity<UserProduct>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__user_pro__3213E83F97CF21F5");

            entity.Property(e => e.BoughtAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Product).WithMany(p => p.UserProducts)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_user_products_products");

            entity.HasOne(d => d.User).WithMany(p => p.UserProducts)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_user_products_users");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}