// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PawPuff_Management.Models.EfModels;

[Table("point_change_types")]
[Index("ActionName", Name = "UQ_point_change_types_action_name", IsUnique = true)]
public partial class PointChangeType
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("action_name")]
    [StringLength(50)]
    [Unicode(false)]
    public string ActionName { get; set; }

    [Column("is_fixed")]
    public bool IsFixed { get; set; }

    [Column("default_value")]
    public int? DefaultValue { get; set; }

    [Column("daily_limit")]
    public int? DailyLimit { get; set; }

    [Column("description")]
    [StringLength(100)]
    public string Description { get; set; }

    [InverseProperty("ChangeType")]
    public virtual ICollection<PointTransaction> PointTransactions { get; set; } = new List<PointTransaction>();
}