// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PawPuff_Management.Models.EfModels;

[Table("point_transactions")]
public partial class PointTransaction
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("user_id")]
    public int UserId { get; set; }

    [Column("change_type_id")]
    public int ChangeTypeId { get; set; }

    [Column("point_change")]
    public int PointChange { get; set; }

    [Column("balance_after")]
    public int BalanceAfter { get; set; }

    [Required]
    [Column("description")]
    [StringLength(100)]
    public string Description { get; set; }

    [Column("created_at", TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column("modified_by_admin_id")]
    public int? ModifiedByAdminId { get; set; }

    [Column("user_product_id")]
    public int? UserProductId { get; set; }

    [ForeignKey("ChangeTypeId")]
    [InverseProperty("PointTransactions")]
    public virtual PointChangeType ChangeType { get; set; }

    [ForeignKey("ModifiedByAdminId")]
    [InverseProperty("PointTransactions")]
    public virtual Admin ModifiedByAdmin { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("PointTransactions")]
    public virtual User User { get; set; }

    [ForeignKey("UserProductId")]
    [InverseProperty("PointTransactions")]
    public virtual UserProduct UserProduct { get; set; }
}