// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PawPuff_Management.Models.EfModels;

[Table("products")]
[Index("Name", Name = "IX_products", IsUnique = true)]
[Index("DollBodyId", Name = "IX_products_1", IsUnique = true)]
[Index("DollAccessoryId", Name = "IX_products_2", IsUnique = true)]
[Index("DollFramesId", Name = "IX_products_3", IsUnique = true)]
[Index("DollColorsId", Name = "IX_products_4", IsUnique = true)]
public partial class Product
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("name")]
    [StringLength(100)]
    public string Name { get; set; }

    [Required]
    [Column("product_type")]
    [StringLength(50)]
    public string ProductType { get; set; }

    [Column("doll_body_id")]
    public int? DollBodyId { get; set; }

    [Column("doll_accessory_id")]
    public int? DollAccessoryId { get; set; }

    [Column("doll_frames_id")]
    public int? DollFramesId { get; set; }

    [Column("doll_colors_id")]
    public int? DollColorsId { get; set; }

    [Column("price")]
    public int Price { get; set; }

    [Column("is_active")]
    public bool IsActive { get; set; }

    [Column("admin_comment")]
    [StringLength(100)]
    public string AdminComment { get; set; }

    [Column("admin_updated_at", TypeName = "datetime")]
    public DateTime? AdminUpdatedAt { get; set; }

    [Column("modified_by_admin_id")]
    public int? ModifiedByAdminId { get; set; }

    [ForeignKey("DollAccessoryId")]
    [InverseProperty("Product")]
    public virtual DollAccessory DollAccessory { get; set; }

    [ForeignKey("DollBodyId")]
    [InverseProperty("Product")]
    public virtual DollBody DollBody { get; set; }

    [ForeignKey("DollColorsId")]
    [InverseProperty("Product")]
    public virtual DollColor DollColors { get; set; }

    [ForeignKey("DollFramesId")]
    [InverseProperty("Product")]
    public virtual DollFrame DollFrames { get; set; }

    [ForeignKey("ModifiedByAdminId")]
    [InverseProperty("Products")]
    public virtual Admin ModifiedByAdmin { get; set; }

    [InverseProperty("Product")]
    public virtual ICollection<UserProduct> UserProducts { get; set; } = new List<UserProduct>();
}