// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PawPuff_Management.Models.EfModels;

[Table("tickets")]
public partial class Ticket
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("user_id")]
    public int UserId { get; set; }

    [Required]
    [Column("title")]
    [StringLength(100)]
    public string Title { get; set; }

    [Column("type")]
    public int Type { get; set; }

    [Column("status")]
    public int Status { get; set; }

    [Column("admin_id")]
    public int? AdminId { get; set; }

    [Column("created_at", TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column("end_at", TypeName = "datetime")]
    public DateTime? EndAt { get; set; }

    [Column("last_message_at", TypeName = "datetime")]
    public DateTime? LastMessageAt { get; set; }

    [Column("last_sender_is_admin")]
    public bool? LastSenderIsAdmin { get; set; }

    [ForeignKey("AdminId")]
    [InverseProperty("Tickets")]
    public virtual Admin Admin { get; set; }

    [InverseProperty("Ticket")]
    public virtual ICollection<TicketMessage> TicketMessages { get; set; } = new List<TicketMessage>();

    [ForeignKey("UserId")]
    [InverseProperty("Tickets")]
    public virtual User User { get; set; }
}