// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PawPuff_Management.Models.EfModels;

[Table("ticket_messages")]
public partial class TicketMessage
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("ticket_id")]
    public int TicketId { get; set; }

    [Column("user_id")]
    public int? UserId { get; set; }

    [Column("admin_id")]
    public int? AdminId { get; set; }

    [Required]
    [Column("message_content")]
    [StringLength(1000)]
    public string MessageContent { get; set; }

    [Column("created_at", TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [ForeignKey("AdminId")]
    [InverseProperty("TicketMessages")]
    public virtual Admin Admin { get; set; }

    [ForeignKey("TicketId")]
    [InverseProperty("TicketMessages")]
    public virtual Ticket Ticket { get; set; }

    [InverseProperty("TicketMessages")]
    public virtual ICollection<TicketMessagesImage> TicketMessagesImages { get; set; } = new List<TicketMessagesImage>();

    [ForeignKey("UserId")]
    [InverseProperty("TicketMessages")]
    public virtual User User { get; set; }
}