// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PawPuff_Management.Models.EfModels;

[Table("ticket_messages_images")]
[Index("ImageName", Name = "IX_ticket_messages_images", IsUnique = true)]
public partial class TicketMessagesImage
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("ticket_messages_id")]
    public int TicketMessagesId { get; set; }

    [Required]
    [Column("image_name")]
    [StringLength(50)]
    public string ImageName { get; set; }

    [Column("image_order")]
    public int ImageOrder { get; set; }

    [ForeignKey("TicketMessagesId")]
    [InverseProperty("TicketMessagesImages")]
    public virtual TicketMessage TicketMessages { get; set; }
}