// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PawPuff_Management.Models.EfModels;

[Table("user_doll_configs")]
public partial class UserDollConfig
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("user_id")]
    public int UserId { get; set; }

    [Column("doll_body_id")]
    public int DollBodyId { get; set; }

    [Column("doll_accessory1_id")]
    public int? DollAccessory1Id { get; set; }

    [Column("doll_accessory2_id")]
    public int? DollAccessory2Id { get; set; }

    [Column("doll_accessory3_id")]
    public int? DollAccessory3Id { get; set; }

    [Column("doll_body_color_id")]
    public int? DollBodyColorId { get; set; }

    [Column("doll_accessory1_color_id")]
    public int? DollAccessory1ColorId { get; set; }

    [Column("doll_accessory2_color_id")]
    public int? DollAccessory2ColorId { get; set; }

    [Column("doll_accessory3_color_id")]
    public int? DollAccessory3ColorId { get; set; }

    [ForeignKey("DollAccessory1Id")]
    [InverseProperty("UserDollConfigDollAccessory1s")]
    public virtual DollAccessory DollAccessory1 { get; set; }

    [ForeignKey("DollAccessory1ColorId")]
    [InverseProperty("UserDollConfigDollAccessory1Colors")]
    public virtual DollColor DollAccessory1Color { get; set; }

    [ForeignKey("DollAccessory2Id")]
    [InverseProperty("UserDollConfigDollAccessory2s")]
    public virtual DollAccessory DollAccessory2 { get; set; }

    [ForeignKey("DollAccessory2ColorId")]
    [InverseProperty("UserDollConfigDollAccessory2Colors")]
    public virtual DollColor DollAccessory2Color { get; set; }

    [ForeignKey("DollAccessory3Id")]
    [InverseProperty("UserDollConfigDollAccessory3s")]
    public virtual DollAccessory DollAccessory3 { get; set; }

    [ForeignKey("DollAccessory3ColorId")]
    [InverseProperty("UserDollConfigDollAccessory3Colors")]
    public virtual DollColor DollAccessory3Color { get; set; }

    [ForeignKey("DollBodyId")]
    [InverseProperty("UserDollConfigs")]
    public virtual DollBody DollBody { get; set; }

    [ForeignKey("DollBodyColorId")]
    [InverseProperty("UserDollConfigDollBodyColors")]
    public virtual DollColor DollBodyColor { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("UserDollConfigs")]
    public virtual User User { get; set; }

    [InverseProperty("ActiveDollConfigs")]
    public virtual ICollection<User> Users { get; set; } = new List<User>();
}