// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PawPuff_Management.Models.EfModels;

[Table("user_products")]
[Index("UserId", "ProductId", Name = "UQ_user_products_user_product", IsUnique = true)]
public partial class UserProduct
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("user_id")]
    public int UserId { get; set; }

    [Column("product_id")]
    public int ProductId { get; set; }

    [Column("bought_at", TypeName = "datetime")]
    public DateTime BoughtAt { get; set; }

    [Column("price_snapshot")]
    public int PriceSnapshot { get; set; }

    [InverseProperty("UserProduct")]
    public virtual ICollection<PointTransaction> PointTransactions { get; set; } = new List<PointTransaction>();

    [ForeignKey("ProductId")]
    [InverseProperty("UserProducts")]
    public virtual Product Product { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("UserProducts")]
    public virtual User User { get; set; }
}