// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PawPuff_Management.Models.EfModels;

[Table("users")]
[Index("Account", Name = "UQ_users_account", IsUnique = true)]
[Index("Email", Name = "UQ_users_email", IsUnique = true)]
[Index("Phone", Name = "UQ_users_phone", IsUnique = true)]
public partial class User
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("account")]
    [StringLength(50)]
    [Unicode(false)]
    public string Account { get; set; }

    [Required]
    [Column("password_hash")]
    [StringLength(255)]
    [Unicode(false)]
    public string PasswordHash { get; set; }

    [Required]
    [Column("nickname")]
    [StringLength(100)]
    public string Nickname { get; set; }

    [Required]
    [Column("email")]
    [StringLength(100)]
    public string Email { get; set; }

    [Required]
    [Column("phone")]
    [StringLength(20)]
    public string Phone { get; set; }

    [Column("active_doll_configs_id")]
    public int? ActiveDollConfigsId { get; set; }

    [Column("active_doll_frame_id")]
    public int? ActiveDollFrameId { get; set; }

    [Column("point_balance")]
    public int PointBalance { get; set; }

    [Column("is_active")]
    public bool IsActive { get; set; }

    [Column("created_at", TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column("admin_comment")]
    [StringLength(100)]
    public string AdminComment { get; set; }

    [Column("admin_updated_at", TypeName = "datetime")]
    public DateTime? AdminUpdatedAt { get; set; }

    [Column("modified_by_admin_id")]
    public int? ModifiedByAdminId { get; set; }

    [ForeignKey("ActiveDollConfigsId")]
    [InverseProperty("Users")]
    public virtual UserDollConfig ActiveDollConfigs { get; set; }

    [ForeignKey("ActiveDollFrameId")]
    [InverseProperty("Users")]
    public virtual DollFrame ActiveDollFrame { get; set; }

    [InverseProperty("User")]
    public virtual ICollection<ArticleLike> ArticleLikes { get; set; } = new List<ArticleLike>();

    [InverseProperty("User")]
    public virtual ICollection<ArticleSafe> ArticleSaves { get; set; } = new List<ArticleSafe>();

    [InverseProperty("User")]
    public virtual ICollection<Article> Articles { get; set; } = new List<Article>();

    [InverseProperty("User")]
    public virtual ICollection<Comment> Comments { get; set; } = new List<Comment>();

    [ForeignKey("ModifiedByAdminId")]
    [InverseProperty("Users")]
    public virtual Admin ModifiedByAdmin { get; set; }

    [InverseProperty("User")]
    public virtual ICollection<Notification> Notifications { get; set; } = new List<Notification>();

    [InverseProperty("User")]
    public virtual ICollection<PointTransaction> PointTransactions { get; set; } = new List<PointTransaction>();

    [InverseProperty("User")]
    public virtual ICollection<TicketMessage> TicketMessages { get; set; } = new List<TicketMessage>();

    [InverseProperty("User")]
    public virtual ICollection<Ticket> Tickets { get; set; } = new List<Ticket>();

    [InverseProperty("User")]
    public virtual ICollection<UserDollConfig> UserDollConfigs { get; set; } = new List<UserDollConfig>();

    [InverseProperty("User")]
    public virtual ICollection<UserProduct> UserProducts { get; set; } = new List<UserProduct>();
}